### ISSUE TITLE
Ecko services unable to establish a connection to DNS server, redis-server unable to save data

### ISSUE THREAD

**Issue by jorgesat** [YunoHost-Apps/ecko_ynh#48]
### Describe the bug

Since a few days our ecko installation is working fine for some hours but suddenly loses connection and shows an error screen on the web interface. The issue seems to be related to losing connection to the DNS nameserver (please see logs below) but there is also an issue with redis-server which is unable to save data due to lack of space but there is actually plenty of space on disk (please see redis-server log below).

### Context

- Hardware: VPS bought online 
- YunoHost version: 11.1.6
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: Splitting sidekiq queues into different ones and configuring static IP according to [this](https://docs.hetzner.com/cloud/servers/static-configuration/#disable-cloud-init-network-changes)

### Logs

[ecko-streaming log](https://paste.yunohost.org/icehizimaq)

[ecko-web log](https://paste.yunohost.org/obiguvoyiq)

[redis-server log after restart](https://paste.yunohost.org/efizoqevax)

### Some diagnosis

I have checked for potential issues by looking at the following:

```
# sudo service postgresql status
● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
     Active: active (exited) since Thu 2023-02-09 06:25:40 UTC; 23min ago
   Main PID: 1607 (code=exited, status=0/SUCCESS)
      Tasks: 0 (limit: 18703)
     Memory: 0B
        CPU: 0
     CGroup: /system.slice/postgresql.service

Feb 09 06:25:40 apps.niboe.info systemd[1]: Starting PostgreSQL RDBMS...
Feb 09 06:25:40 apps.niboe.info systemd[1]: Finished PostgreSQL RDBMS.


# ping google.com
PING google.com(par21s22-in-x0e.1e100.net (2a00:1450:4007:819::200e)) 56 data bytes
64 bytes from par21s22-in-x0e.1e100.net (2a00:1450:4007:819::200e): icmp_seq=1 ttl=58 time=35.2 ms
64 bytes from par21s22-in-x0e.1e100.net (2a00:1450:4007:819::200e): icmp_seq=2 ttl=58 time=35.1 ms
64 bytes from par21s22-in-x0e.1e100.net (2a00:1450:4007:819::200e): icmp_seq=3 ttl=58 time=35.2 ms
64 bytes from par21s22-in-x0e.1e100.net (2a00:1450:4007:819::200e): icmp_seq=4 ttl=58 time=35.1 ms
64 bytes from par21s22-in-x0e.1e100.net (2a00:1450:4007:819::200e): icmp_seq=5 ttl=58 time=35.1 ms
64 bytes from par21s22-in-x0e.1e100.net (2a00:1450:4007:819::200e): icmp_seq=6 ttl=58 time=35.1 ms
64 bytes from par21s22-in-x0e.1e100.net (2a00:1450:4007:819::200e): icmp_seq=7 ttl=58 time=35.1 ms
64 bytes from par21s22-in-x0e.1e100.net (2a00:1450:4007:819::200e): icmp_seq=8 ttl=58 time=35.2 ms
^C
--- google.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7005ms
rtt min/avg/max/mdev = 35.079/35.138/35.221/0.043 ms


# tail syslog
Feb  9 06:51:09 apps bundle[1639]: [1548b7e4-82dc-4706-ab14-bd65090bc9b4]
Feb  9 06:51:09 apps bundle[1639]: [1548b7e4-82dc-4706-ab14-bd65090bc9b4] ActiveRecord::ConnectionNotEstablished (could not connect to server: Connection refused
Feb  9 06:51:09 apps bundle[1639]: #011Is the server running on host "localhost" (127.0.0.1) and accepting
Feb  9 06:51:09 apps bundle[1639]: #011TCP/IP connections on port 5432?
Feb  9 06:51:09 apps bundle[1639]: ):
Feb  9 06:51:09 apps bundle[1639]: [1548b7e4-82dc-4706-ab14-bd65090bc9b4]
Feb  9 06:51:09 apps bundle[1639]: [1548b7e4-82dc-4706-ab14-bd65090bc9b4] app/models/ip_block.rb:31:in `block in blocked?'
Feb  9 06:51:09 apps bundle[1639]: [1548b7e4-82dc-4706-ab14-bd65090bc9b4] app/models/ip_block.rb:31:in `blocked?'
Feb  9 06:51:09 apps bundle[1639]: [1548b7e4-82dc-4706-ab14-bd65090bc9b4] config/initializers/rack_attack.rb:62:in `block in <class:Attack>'
Feb  9 06:51:09 apps bundle[1846]: 2023-02-09T06:51:09.704Z pid=1846 tid=29f2 ERROR: heartbeat: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.



# status ecko-sidekiq-pull-2.service
● ecko-sidekiq-pull-2.service - ecko-sidekiq-pull-2
     Loaded: loaded (/etc/systemd/system/ecko-sidekiq-pull-2.service; disabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-02-09 06:26:03 UTC; 25min ago
   Main PID: 1852 (bundle)
      Tasks: 71 (limit: 18703)
     Memory: 427.8M
        CPU: 2min 17.232s
     CGroup: /system.slice/ecko-sidekiq-pull-2.service
             └─1852 sidekiq 6.4.0 live [0 of 65 busy]

Feb 09 06:51:47 apps.niboe.info bundle[1852]: /var/www/ecko/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/api.rb:783>
Feb 09 06:51:47 apps.niboe.info bundle[1852]: /var/www/ecko/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/api.rb:776>
Feb 09 06:51:47 apps.niboe.info bundle[1852]: /var/www/ecko/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/scheduled.>
Feb 09 06:51:47 apps.niboe.info bundle[1852]: /var/www/ecko/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/scheduled.>
Feb 09 06:51:47 apps.niboe.info bundle[1852]: /var/www/ecko/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/scheduled.>
Feb 09 06:51:47 apps.niboe.info bundle[1852]: /var/www/ecko/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/scheduled.>
Feb 09 06:51:47 apps.niboe.info bundle[1852]: /var/www/ecko/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/scheduled.>
Feb 09 06:51:47 apps.niboe.info bundle[1852]: /var/www/ecko/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/util.rb:56>
Feb 09 06:51:47 apps.niboe.info bundle[1852]: /var/www/ecko/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.0/lib/sidekiq/util.rb:65>
Feb 09 06:51:50 apps.niboe.info bundle[1852]: 2023-02-09T06:51:50.094Z pid=1852 tid=6c48 ERROR: heartbeat: MISCONF Redis is configu>


# resolvectl status
Global
         Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: foreign
Current DNS Server: 127.0.0.1
       DNS Servers: 127.0.0.1

Link 2 (eth0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

```

**Comment by weex** [comment]
I don't see any measurement of disk space. Can you post the output of `df -h`?

**Comment by jorgesat** [comment]
Sorry, it seems we were actually quite running out of space. I did not notice the logs were occupying so much disk space. The issue seems to be solved after freeing up some space.
